### ISSUE TITLE
Android tests

### ISSUE THREAD

**Issue by bmichotte** [rubymotion/sugarcube#201]
Hi @colinta,

I was trying to get some tests running for Android as I should soon send a PR for some stuff. 

Could you get something running ? I pushed on https://github.com/bmichotte/sugarcube/tree/android-stuff my unsuccessfull attempt

FYI, this is the error I receive

```
E/AndroidRuntime( 9873): FATAL EXCEPTION: main
E/AndroidRuntime( 9873): Process: com.yourcompany.sugarcube, PID: 9873
E/AndroidRuntime( 9873): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.yourcompany.sugarcube/com.yourcompany.sugarcube.MainActivity}: com.rubymotion.NoMethodError: undefined method `[]' for nil:NilClass
E/AndroidRuntime( 9873): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2313)
E/AndroidRuntime( 9873): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2375)
E/AndroidRuntime( 9873): 	at android.app.ActivityThread.access$900(ActivityThread.java:144)
E/AndroidRuntime( 9873): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1293)
E/AndroidRuntime( 9873): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 9873): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 9873): 	at android.app.ActivityThread.main(ActivityThread.java:5238)
E/AndroidRuntime( 9873): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 9873): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 9873): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:931)
E/AndroidRuntime( 9873): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:726)
E/AndroidRuntime( 9873): Caused by: com.rubymotion.NoMethodError: undefined method `[]' for nil:NilClass
E/AndroidRuntime( 9873): 	at com.yourcompany.sugarcube.MainActivity.onCreate(Native Method)
E/AndroidRuntime( 9873): 	at android.app.Activity.performCreate(Activity.java:5941)
E/AndroidRuntime( 9873): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
E/AndroidRuntime( 9873): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2266)
E/AndroidRuntime( 9873): 	... 10 more
```

**Comment by colinta** [comment]
Hmm that's a strange error - thanks for starting down this road!  When I started on Android support, I thought I was going to be working on an Android app imminently (didn't happen, obviously).  Glad to get started on this again.
