### ISSUE TITLE
 undefined method `days'

### ISSUE THREAD

**Issue by mytrackz** [rubymotion/sugarcube#204]
2015-08-05 22:37:54.916 9.01 playingaudio[39954:1027409] nsdate.rb:260:in `start_of_week:': undefined method `days' for 2:Fixnum (NoMethodError)
	from SinglesTableController.rb:121:in `tableView:cellForRowAtIndexPath:'
2015-08-05 22:37:54.920 9.01 playingaudio[39954:1027409] *** Terminating app due to uncaught exception 'NoMethodError', reason: 'nsdate.rb:260:in `start_of_week:': undefined method `days' for 2:Fixnum (NoMethodError)
	from SinglesTableController.rb:121:in `tableView:cellForRowAtIndexPath:'
'

keep getting this error when trying to use the method `start_of_week:':

**Comment by colinta** [comment]
Hmm, try requiring the `sugarcube-numbers` package.

**Comment by mytrackz** [comment]
ok ill give it a shot

**Comment by mytrackz** [comment]
worked fine cheers

**Comment by colinta** [comment]
Nice!  Anything else?  Please close the issue if it’s resolved.
